### ISSUE TITLE
Error with Quickstart demo

### ISSUE THREAD

**Issue by Proudspark** [rwbutler/AnimatedGradientView#1]
Successfully installed via cocoapods. Added `import AnimatedGradientView` (might be worth putting this step to your Quickstart instructions?).

Not able to test your Quickstart code, as I'm receiving the following error:

`Value of type 'AnimatedGradientView' has no member 'animationValues'`

Am I missing something obvious? Thanks.

**Comment by rwbutler** [comment]
Consider it added 🙂As for the issue with the `animationValues` property not being visible, I'm not certain what the issue would be here. I just created a brand new Swift 4.2 project, added the framework using Cocoapods and pasted the sample code which seems to run fine. Is there anything more you could tell me about your setup that might shed some light on this? Are you able to compile and run the Example app included in this repo OK?

**Comment by Proudspark** [comment]
I too managed to get the Example app working, and also built a new project simply adding the code snippet - which also worked... (Last line changed to this: `self.view?.addSubview(animatedGradient)`)

At the mo the only difference I can see is that in newly created project snippet is in: 
```
override func viewDidLoad() {
        //// here
        let animatedGradient = AnimatedGradientView(frame: view.bounds)
        animatedGradient.direction = .up
        animatedGradient.animationValues = [(colors: ["#2BC0E4", "#EAECC6"], .up, .axial),
                                            (colors: ["#833ab4", "#fd1d1d", "#fcb045"], .right, .axial),
                                            (colors: ["#003973", "#E5E5BE"], .down, .axial),
                                            (colors: ["#1E9600", "#FFF200", "#FF0000"], .left, .axial)]
        self.view?.addSubview(animatedGradient)
}
```
In my main project it's being called from:
```
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
       /// here
}
```

But I can't see why this would make a difference.

Perhaps there is a conflict in my podfile?
```
platform :ios, '9.2'

target 'Kylypso' do
  use_frameworks!
  pod "AudioKit", '~> 4.4'
  pod "TouchVisualizer", '~>3.0.2'
  pod "AnimatedGradientView"
  
  pod 'FacebookCore'
  
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
    

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
```

**Comment by rwbutler** [comment]
Thanks for the information. My best guess at the moment is that the compiler is seeing the type of your view in your main project as `UIView` rather than as of type `AnimatedGradientView` which would explain why the compiler doesn't see the `animationValues` property.

You should be able to determine the type by adding a line such as `print(type(of: myView))` before the line which reads:
```swift
myView.animationValues = ...
```

Could you run this line and see what is printed?

**Comment by Proudspark** [comment]
So, in order to discover the View type, I commented out the `animationValues` line. Then I saw the gradient (on a default colour?) - and type was indeed returned as `AnimatedGradientView`... The mystery deepens 🧐

**Comment by rwbutler** [comment]
That is a mystery - I created a new project with your Podfile and again everything worked fine. Are you using an older version of Swift in your project or is there anything else notable about your setup you can think of?

**Comment by Proudspark** [comment]
Solved - simple when you know how. I'd changed Swift from 4.0 - 4.2 in Pods project, but not in main... D'oh! 

Thanks so much for your input on this - it did help me find the issue. Aaaand, those gradients are beautiful! 😎

**Comment by rwbutler** [comment]
Glad you solved it! 😃
