### ISSUE TITLE
Radial gradient does not have radius parameter

### ISSUE THREAD

**Issue by aritroper** [rwbutler/AnimatedGradientView#14]
How can I change the size of the inner gradient circle of a radial gradient?

**Comment by rwbutler** [comment]
Hi @aritroper, this should just be a matter of setting the gradient type to `radial` and then setting the `locations` property of the `Animation` object appropriately. These values are mapped by the library to the [`locations`](https://developer.apple.com/documentation/quartzcore/cagradientlayer/1462410-locations) property of the `CAGradientLayer`. Hope this helps a little!
