### ISSUE TITLE
[Question] update colours array

### ISSUE THREAD

**Issue by esmondmissen** [rwbutler/AnimatedGradientView#16]
HI I was just wondering if it was at all possible to update the UIColors while the animation is playing? All my experiments so far have been unsuccessful.

**Comment by rwbutler** [comment]
Could let me know a little bit more about what you're attempting to achieve? It should be possible to update the colours dynamically if required

**Comment by rwbutler** [comment]
@esmondmissen I'm going to close this one for now but happy to re-open if it turns out this is still an issue for you. Let me know if you have any further information.
