### ISSUE TITLE
[Feature request] Pause animation

### ISSUE THREAD

**Issue by aritroper** [rwbutler/AnimatedGradientView#17]
Stopping the animation seems to reset the color gradient, but I'm wondering if there is a way to 'pause' the animation such that when paused the gradient colors don't reset, and when startAnimation() is called, the animation picks up from the paused state. Thanks

**Comment by thatcherclough** [comment]
This would be great!

**Comment by rwbutler** [comment]
@aritroper @thatcherclough As part of [release 3.1.0](https://github.com/rwbutler/AnimatedGradientView/releases/tag/3.1.0) I've added the functions `pauseAnimating` and `resumeAnimating` which hopefully should do what you're after. Hope this helps!
