### ISSUE TITLE
Working with SKSpriteNodes

### ISSUE THREAD

**Issue by Proudspark** [rwbutler/AnimatedGradientView#2]
Hi again. Not an issue, more a query, so I hope it's OK to post here?

I'm working with a gamescene (SKscene) using lots of nodes with moving sprites etc. I'm trying to insert the AnimatedGradientView between sprite nodes and Background image nodes. When I add it as a new view, it defaults to a layer above all the SKScene nodes.

Is there a way to add AnimatedGradientView to a SKSpriteNode? Been scratching my head on this...

🤔

**Comment by rwbutler** [comment]
No problem, if you're adding your `animatedGradientView` to a parent view e.g.

```swift
view.addSubview(animatedGradientView)
```

You should then be able to send it to back using:

```swift
view.sendSubviewToBack(animatedGradientView)
```

As for adding to a SKSpriteNode, this won't be possible because a SKSpriteNode is not part of the view hierarchy. Hope this helps a little?

**Comment by Proudspark** [comment]
Again thanks for the super quick response 🔆 Been trying this, but getting some issues.

```
self.view?.addSubview(animatedGradient) // successfully adds to SKScene
```

It's when I try `sendSubviewToBack` that I see issues:

```
        // attempt 1
        self.view?.sendSubviewToBack(animatedGradient)
        // error: Use of unresolved identifier 'animatedGradient'; did you mean 'AnimatedGradientView'?
        
        // attempt 2
        self.view?.sendSubviewToBack(AnimatedGradientView)
        // error: Cannot convert value of type '(AnimatedGradientView).Type' to expected argument type 'UIView'
        
        // attempt 3
        self.view?.sendSubviewToBack(self.view?.AnimatedGradientView)
        // error: Value of type 'SKView' has no member 'AnimatedGradientView'
        
        // attempt 4
        AnimatedGradientView.superview?.bringSubviewToFront(AnimatedGradientView)
        // error: Instance member 'superview' cannot be used on type 'AnimatedGradientView'
```

I do have this method working from before with other elements. Eg:
```
self.view?.bringSubviewToFront(parentController.some_button) // button on ViewController
self.view?.sendSubviewToBack(cameraPreview) // UIView
```

Any clues? Thanks a million!

**Comment by rwbutler** [comment]
No problem - attempt 1 should work just fine. Is the line ‘sendSubviewToBack’ immediately after    the first line or is it in a different method? So long as the variable ‘animatedGradient’ is in scope there shouldn’t be any issue using it in this way. Would it be possible to supply more of the surrounding code for context?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Proudspark** [comment]
😇 Ah yes, you were right. I had moved the `sendSubviewToBack` to a `sortSubviewLayers` function and of course `animatedGradient` was out of scope. Easy when you know how! Really appreciate your help.

I'm still trying to arrange UIViews and SKView in terms of layers, and I might be trying to do the impossible. Couple of questions (if you don't mind 🤩)...

Can AnimatedGradient be added to a CALayer so I can add it to SKView?
Can SKView be placed above a UIView (is that what `.allowsTransparency` is for?)?

[Researching now...]

👍

**Comment by rwbutler** [comment]
Glad you've found the issue. You can add UIViews as subviews of other UIViews and you can add CALayers as sublayers of other CALayers but you cannot add a view to layer. Also worth knowing that every UIView has a CALayer (accessed via the `layer` property).

So you may add an AnimatedGradientView as a subview of an SKView and add an SKView as a subview of a UIView (or the other way around).

If you want a transparent view you need to set `opaque` to `false` (https://developer.apple.com/documentation/uikit/uiview/1622622-opaque) and then set the background color to `UIColor.clear`.

Hope this helps a bit 🙂

**Comment by Proudspark** [comment]
Those insights, simply put, helped me no end. Figured out how to layer all my UIviews, with glorious gradients too. Again thanks!

**Comment by rwbutler** [comment]
No problem 🙂👍🏻
