### ISSUE TITLE
Sample code is no good

### ISSUE THREAD

**Issue by adamdahan** [rwbutler/AnimatedGradientView#3]
AnimationGradientView does not have animationValues property.

**Comment by adamdahan** [comment]
![Screen Shot 2019-04-06 at 1 31 25 PM](https://user-images.githubusercontent.com/1205894/55673025-5197e000-5870-11e9-8c5d-0c8698e22dd7.png)

**Comment by adamdahan** [comment]
Running iOS 12

**Comment by rwbutler** [comment]
Could you tell me are you using Cocoapods? If so, could you check the Swift version in use in your Pods project and the Swift version in use in your app (in Build Settings) and tell what versions these are set to? Thanks.

**Comment by rwbutler** [comment]
I'm going to go ahead and close this one for now - if you manage to find out which version of Swift you are using let me know and we'll re-open 👍🏻
