### ISSUE TITLE
Swift 5.0

### ISSUE THREAD

**Issue by Proudspark** [rwbutler/AnimatedGradientView#4]
Hi Ross... Can't compile currently in Xcode 10.2.

Updated all pods, changed Build Settings/Swift Language Version in main project and pod project to 5.0 (necessary?)

Getting error:
``` Use of unresolved identifier '_debugPrecondition'```
referring to line 14 of Collection+UniqueMap.swift

**Comment by rwbutler** [comment]
I've created a branch called "swift-5" so if you switch to using that it should be compatible with your project.

For Cocoapods:
```
pod 'AnimatedGradientView', :git => 'https://github.com/rwbutler/AnimatedGradientView.git', :branch => 'swift-5'
```

For Carthage:

```
github "rwbutler/AnimatedGradientView" "swift-5"
```

**Comment by Proudspark** [comment]
Fantastic - all good. Thx 😎
